# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: luisdanieldlcg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: thryv-backend
# "service" is the name of this project. This will also be added to your AWS resource names.
service: thryv-hackaton

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:677276097870:table/users
functions:
  registerUser:
    handler: src/routes/auth.register
    events:
      - httpApi:
          path: /auth/register
          method: post
  loginUser:
    handler: src/routes/auth.login
    events:
      - httpApi:
          path: /auth/login
          method: post

resources:
  Resources:
    users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
