# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: luisdanieldlcg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: thryv-backend
# "service" is the name of this project. This will also be added to your AWS resource names.
service: thryv-hackaton

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  httpApi:
    cors: true
functions:
  registerUser:
    handler: src/routes/auth.register
    events:
      - httpApi:
          path: /auth/register
          method: post

  loginUser:
    handler: src/routes/auth.login
    events:
      - httpApi:
          path: /auth/login
          method: post
  configureProfile:
    handler: src/routes/user.saveCompany
    events:
      - httpApi:
          path: /user/configure
          method: post

plugins:
  - serverless-offline
